#!/bin/php
<?php
/*
 * This file is part of the Bot Web Handler project.
 * Copyright 2024-2024 Ismail Aatif
 * https://github.com/ismailian/bot-web-handler
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use TeleBot\System\Cli;
use Clue\Commander\Router;
use TeleBot\System\QueueWorker;
use TeleBot\System\Filesystem\Dotenv;

require_once 'vendor/autoload.php';

Dotenv::load();

/**
 * registered commands
 */
$router = new Router();

/* system update command */
$router->add('update:init', fn($args) => Cli::init());
$router->add('update:check', fn($args) => Cli::check());
$router->add('update:apply', fn($args) => Cli::update());

/* handler commands */
$router->add('handler:make <name>', fn($args) => Cli::makeHandler($args));
$router->add('handler:delete <name>', fn($args) => Cli::deleteHandler($args));

/* migration commands */
$router->add('migrate [<tables>...]', fn($args) => Cli::migrate($args));

/* queue commands */
$router->add('queue:init', fn($args) => QueueWorker::init());
$router->add('queue:work', fn($args) => QueueWorker::listen());

/* webhook commands */
$router->add('webhook:set [<uri>]', fn($args) => Cli::setWebhook($args));
$router->add('webhook:unset', fn($args) => Cli::unsetWebhook());

$router->execArgv();
