#!/bin/php
<?php
/*
 * This file is part of the Bot Web Handler project.
 * Copyright 2024-2024 Ismail Aatif
 * https://github.com/ismailian/bot-web-handler
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use TeleBot\System\Filesystem\Dotenv;
use TeleBot\System\Interfaces\IScript;

require __DIR__ . '/vendor/autoload.php';

if (count($argv) < 2) return;

/**
 * initialize and run procedure
 */
$procedure = $argv[1];
$procedure = "TeleBot\App\Scripts\\$procedure";
if (is_subclass_of($procedure, IScript::class)) {
    Dotenv::load();
    (new $procedure())->run();
}