#!/bin/php
<?php
/*
 * This file is part of the Bot Web Handler project.
 * Copyright 2024-2024 Ismail Aatif
 * https://github.com/ismailian/bot-web-handler
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use TeleBot\System\Core\Bootstrap;
use TeleBot\System\Interfaces\IScript;

require __DIR__ . '/vendor/autoload.php';

if (count($argv) < 2) return;

/**
 * initialize and run procedure
 */
$script = $argv[1];
$script = "TeleBot\App\Scripts\\$script";
if (is_subclass_of($script, IScript::class)) {
    Bootstrap::init();
    new $script()->run();
}